### ISSUE TITLE
채널 생성 오류

### ISSUE THREAD

**Issue by kms0219kms** [mswgen/adbot#1]
이거 포크해서 채널 ID 같은거 수정하고 실행했는데 channel이 정의 되지 않았답니다. 왜 그런건가요?

**Comment by norhu1130** [comment]
(node:11028) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'channels' 
of undefined
    at Client.<anonymous> (/home/runner/adbot/bot.js:62:56)
    at Client.emit (events.js:315:20)
    at GuildDeleteAction.handle (/home/runner/adbot/node_modules/discord.js/src/client/act
ions/GuildDelete.js:51:14)
    at Object.module.exports [as GUILD_DELETE] (/home/runner/adbot/node_modules/discord.js
/src/client/websocket/handlers/GUILD_DELETE.js:4:30)
    at WebSocketManager.handlePacket (/home/runner/adbot/node_modules/discord.js/src/clien
t/websocket/WebSocketManager.js:386:31)
    at WebSocketShard.onPacket (/home/runner/adbot/node_modules/discord.js/src/client/webs
ocket/WebSocketShard.js:436:22)
    at WebSocketShard.onMessage (/home/runner/adbot/node_modules/discord.js/src/client/web
socket/WebSocketShard.js:293:10)
    at WebSocket.onMessage (/home/runner/adbot/node_modules/ws/lib/event-target.js:125:16)
    at WebSocket.emit (events.js:315:20)
    at Receiver.receiverOnMessage (/home/runner/adbot/node_modules/ws/lib/websocket.js:797
:20)
(node:11028) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error ori
ginated either by throwing inside of an async function without a catch block, or by reject
ing a promise which was not handled with .catch(). To terminate the node process on unhand
led promise rejection, use the CLI flag --unhandled-rejections=strict (see https://nodej/
s.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:11028) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In
 the future, promise rejections that are not handled will terminate the Node.js process wi
th a non-zero exit code.
(node:11028) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'channels' 
of undefined
at createChannel (/home/runner/adbot/scripts/guildAdd2.mswgen:41:58)
    at Object.func [as guildAdd] (/home/runner/adbot/scripts/guildAdd2.mswgen:6:13)
    at Client.<anonymous> (/home/runner/adbot/bot.js:59:19)
    at Client.emit (events.js:315:20)
    at Object.module.exports [as GUILD_CREATE] (/home/runner/adbot/node_modules/discord.js
/src/client/websocket/handlers/GUILD_CREATE.js:33:14)
    at WebSocketManager.handlePacket (/home/runner/adbot/node_modules/discord.js/src/clien
t/websocket/WebSocketManager.js:386:31)
    at WebSocketShard.onPacket (/home/runner/adbot/node_modules/discord.js/src/client/webs
ocket/WebSocketShard.js:436:22)
    at WebSocketShard.onMessage (/home/runner/adbot/node_modules/discord.js/src/client/websocket/WebSocketShard.js:293:10)
    at WebSocket.onMessage (/home/runner/adbot/node_modules/ws/lib/event-target.js:125:16)
    at WebSocket.emit (events.js:315:20)
(node:11028) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag --unhandled-rejections=strict (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)

오류내용입니다

**Comment by mswgen** [comment]
흠
저도 잘 모르겠네요..
cliet is not defined 안떴어요?
그러면 도대체 뭘까요...

**Comment by mswgen** [comment]
혹시 포크한 레포지토리 볼 수 있을까요?

**Comment by mswgen** [comment]
@kms0219kms

**Comment by mswgen** [comment]
@norhu1130

**Comment by norhu1130** [comment]
네 잠시만요

**Comment by kms0219kms** [comment]
https://github.com/hongboworld/MainBot

**Comment by mswgen** [comment]
@kms0219kms ![Screenshot_20200802-181142_GitHub.jpg](https://user-images.githubusercontent.com/54498184/89119754-af334f80-d4eb-11ea-96bb-e5fd080c1d63.jpg)

**Comment by kms0219kms** [comment]
초대해 드릴게요
